"""Neovim plugin for day/night cycle automation."""

import subprocess
from pathlib import Path
from typing import Optional
from .base import Plugin


class NeovimPlugin(Plugin):
    """
    Plugin to control Neovim colorscheme.

    This plugin writes a theme configuration file that Neovim can source.
    It supports both background setting and specific colorscheme names.
    """

    def __init__(self, config):
        super().__init__(config)
        # Neovim theme file path
        self.theme_path = Path.home() / '.config' / 'nvim' / 'theme.lua'

    @property
    def name(self) -> str:
        return "neovim"

    def validate_config(self) -> tuple[bool, Optional[str]]:
        """Validate Neovim configuration directory exists."""
        nvim_config_dir = Path.home() / '.config' / 'nvim'
        if not nvim_config_dir.exists():
            return False, f"Neovim config directory not found at {nvim_config_dir}"
        return True, None

    def _update_theme(self, mode: str) -> bool:
        """
        Update Neovim theme by writing a theme configuration file.

        Args:
            mode: 'light' or 'dark'

        Returns:
            True if successful, False otherwise
        """
        try:
            # Get colorscheme from config or use background setting
            colorscheme = self.config.get(f'{mode}_colorscheme')

            # Build the Lua script
            if colorscheme:
                # Use specific colorscheme if provided
                lua_content = f'''-- Auto-generated by day-night-cycle
-- Set colorscheme to {mode} mode
vim.o.background = "{mode}"
vim.cmd.colorscheme("{colorscheme}")
'''
            else:
                # Just set background, let theme adapt
                lua_content = f'''-- Auto-generated by day-night-cycle
-- Set background to {mode} mode
vim.o.background = "{mode}"
'''

            # Ensure directory exists
            self.theme_path.parent.mkdir(parents=True, exist_ok=True)

            # Write the theme file
            with open(self.theme_path, 'w') as f:
                f.write(lua_content)

            # Try to notify running Neovim instances
            self._notify_running_instances(mode, colorscheme)

            return True
        except FileNotFoundError as e:
            print(f"    Error: Neovim config directory not found: {e}")
            return False
        except Exception as e:
            print(f"    Error: {e}")
            return False

    def _notify_running_instances(self, mode: str, colorscheme: Optional[str]):
        """
        Attempt to notify running Neovim instances to reload theme.

        This is best-effort - if it fails, the theme will still be applied
        on next Neovim start.

        Args:
            mode: 'light' or 'dark'
            colorscheme: Optional specific colorscheme name
        """
        try:
            # Try using nvim --remote-expr to update running instances
            # This requires neovim-remote or nvim with --remote support
            if colorscheme:
                commands = [
                    f'vim.o.background = "{mode}"',
                    f'vim.cmd.colorscheme("{colorscheme}")'
                ]
            else:
                commands = [f'vim.o.background = "{mode}"']

            for cmd in commands:
                # Try both nvr (neovim-remote) and nvim --remote-expr
                for remote_cmd in [['nvr', '--remote-expr'], ['nvim', '--remote-expr']]:
                    try:
                        subprocess.run(
                            remote_cmd + [cmd],
                            check=False,  # Don't fail if no running instance
                            capture_output=True,
                            timeout=2
                        )
                        break  # If one worked, don't try the other
                    except (subprocess.TimeoutExpired, FileNotFoundError):
                        continue
        except Exception:
            # Silently ignore errors - this is best-effort
            pass

    def set_light_mode(self) -> bool:
        """Set Neovim to light theme."""
        return self._update_theme('light')

    def set_dark_mode(self) -> bool:
        """Set Neovim to dark theme."""
        return self._update_theme('dark')
