package plugins

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
)

// Neovim writes theme configuration file.
func Neovim(cfg map[string]interface{}, isLight bool) error {
	mode := "dark"
	colorschemeKey := "dark_colorscheme"
	if isLight {
		mode = "light"
		colorschemeKey = "light_colorscheme"
	}

	themePath := filepath.Join(os.Getenv("HOME"), ".config/nvim/theme.lua")

	var content string
	if colorscheme, ok := cfg[colorschemeKey].(string); ok {
		content = fmt.Sprintf(`-- Auto-generated by day-night-cycle
-- Set colorscheme to %s mode
vim.o.background = "%s"
vim.cmd.colorscheme("%s")
`, mode, mode, colorscheme)
	} else {
		content = fmt.Sprintf(`-- Auto-generated by day-night-cycle
-- Set background to %s mode
vim.o.background = "%s"
`, mode, mode)
	}

	if err := os.MkdirAll(filepath.Dir(themePath), 0755); err != nil {
		return err
	}

	if err := os.WriteFile(themePath, []byte(content), 0644); err != nil {
		return err
	}

	// Best effort: try to notify running Neovim instances
	notifyNeovim(themePath)

	return nil
}

// notifyNeovim attempts to notify running Neovim instances (best effort).
func notifyNeovim(themePath string) {
	// Try nvr (neovim-remote) first
	cmd := exec.Command("nvr", "--remote-expr", fmt.Sprintf("luafile %s", themePath))
	_ = cmd.Run()

	// Try nvim --remote-expr as fallback
	if cmd.ProcessState != nil && !cmd.ProcessState.Success() {
		cmd = exec.Command("nvim", "--remote-expr", fmt.Sprintf("luafile %s", themePath))
		_ = cmd.Run()
	}
}
